# https://cloud.google.com/vision/automl/object-detection/docs/edge-quickstart
# https://cloud.google.com/vision/automl/object-detection/docs/prepare
# 1024 pixels by 1024 pixels suggested maximum
# 10 annotations (instances) minimum
# 100 annotations per label
# 100x more images for the most common label than for the least common label.


footage_path: "~/projects/footage/"
footage_files:
    - 10MinVid_cut.mp4
    - distances_testing_welshpool_floor.mkv
width: 1024
height: 1024
display_height: 1080
display_width: 1920

model_path: "/models/coraledgetpu"
model: "mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite"
labels_file: "coco_labels.txt"
detect_objects: 
    - all
    - person
    - car   
confidence: 0.7

image_output_path: "~/projects/footage/automl"


# TRAIN,gs://cloud-ml-data/img/openimage/3/2520/3916261642_0a504acd60_o.jpg,Salad,0.0,0.0954,,,0.977,0.957,,
# VALIDATE,gs://cloud-ml-data/img/openimage/3/2520/3916261642_0a504acd60_o.jpg,Seafood,0.0154,0.1538,,,1.0,0.802,,
# TEST,gs://cloud-ml-data/img/openimage/3/2520/3916261642_0a504acd60_o.jpg,Tomato,0.0,0.655,,,0.231,0.839,,